### ISSUE TITLE
Spectrum Analyzer might be crashing Dopamine

### ISSUE THREAD

**Issue by neilunderwood** [digimezzo/dopamine-windows#1026]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 1903 (18362.295)
* Dopamine version: 2.0 preview 9

## Reproduction steps

* Step 1 - open dopamine and hope it doesn't crash and close immediately
* Step 2 - Attempt to play literally anything
* Step 3 - watch it crash and close

## Observed behavior

It just closes as soon as I try to play something
## Desired behavior

It should play the audio files
## Log file

Add the relevant piece of the log file. The Dopamine log file can be found in this directory: %appdata%\Dopamine\Log

Here is an example from the log:
`2019-08-28 10:22:03.760|Info|PlaybackService.TryPlayAsync|1127|Playing the file G:\Music\AC-DC\1975_-_High_Voltage\01_-_It_s_a_Long_Way_to_the_Top__If_You_Wanna_Rock__n__Roll_.ogg. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False
2019-08-28 10:22:03.763|Info|PlaybackService.GetSavedQueuedTracks|1293|Starting track G:\Music\AC-DC\1986_-_Who_Made_Who\01_-_Who_Made_Who.ogg paused
2019-08-28 10:22:04.210|Info|UpdateService.CheckNow|273|Update check: new online version = 0.0.0.0...
2019-08-28 10:22:04.210|Info|UpdateService.CheckNow|396|No new version was found
2019-08-28 10:22:04.265|Error|App.xaml.ExecuteEmergencyStop|541|Unhandled Exception. Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrumShapes()
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrum()
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Stack trace:
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrumShapes()
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrum()
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2019-08-28 10:22:04.265|Info|App.xaml.ExecuteEmergencyStop|544|### FORCED STOP of Dopamine, version 2.0.0.1009 ###
2019-08-28 10:22:04.735|Info|PlaybackService.TryPlayAsync|1127|Playing the file G:\Music\AC-DC\1986_-_Who_Made_Who\01_-_Who_Made_Who.ogg. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False
2019-08-28 10:22:04.782|Info|Shell.xaml.Window_Closing|124|### STOPPING Dopamine, version 2.0.0.1009 ###`

**Comment by neilunderwood** [comment]
Still having issues after disabling spectrum analyzer.  After disabling visualizations it worked all day for me.  This morning the application won't even launch, citing .NET errors.  Here are the errors I'm seeing:

`Application: Dopamine.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at SQLitePCL.SQLite3Provider_e_sqlite3+NativeMethods.sqlite3_finalize(IntPtr)
   at SQLitePCL.raw.sqlite3_finalize(SQLitePCL.sqlite3_stmt)
   at SQLite.PreparedSqlLiteInsertCommand.Dispose(Boolean)
   at SQLite.PreparedSqlLiteInsertCommand.Finalize()`

`Faulting application name: Dopamine.exe, version: 2.0.0.1009, time stamp: 0x5d210b44
Faulting module name: ntdll.dll, version: 10.0.18362.267, time stamp: 0xc00f8a30
Exception code: 0xc0000005
Fault offset: 0x000000000001b39d
Faulting process id: 0x2e5c
Faulting application start time: 0x01d55dc4f7f196ad
Faulting application path: C:\Program Files (x86)\Dopamine\Dopamine.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 1eff47c1-2ec6-4180-ae5c-391065aa6c33
Faulting package full name: 
Faulting package-relative application ID: `

**Comment by digimezzo** [comment]
Could you update to the latest preview? This bug should be fixed.

**Comment by neilunderwood** [comment]
I'm sorry.  I though 9 was the latest.  The sorting threw me off.  Going to try preview 13 right now.

**Comment by neilunderwood** [comment]
Seems to be working fine now on Preview 13 with spectrum analyzer enabled.  Sorry I missed that.  And BTW thank you for the awesome software.  This application has the best combination of aesthetics and functionality of any player I've ever used, and I've been at this for a long time.
