### ISSUE TITLE
Spectrum analyzer causes IndexOutOfRangeException

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#1111]

**Comment by digimezzo** [comment]
2020-03-11 11:23:39.149|Info|CollectionFoldersSettingsViewModel.AddFolder|130|Adding a folder to the collection.
2020-03-11 11:23:47.794|Info|FolderRepository.AddFolderAsync|35|Added the Folder E:\Music\MP3\MP3s
2020-03-11 11:23:50.730|Info|IndexingService.CheckCollectionAsync|143|+++ STARTED CHECKING COLLECTION +++
2020-03-11 11:23:51.795|Info|IndexingService.IndexTracksAsync|274|+++ STARTED INDEXING COLLECTION +++
2020-03-11 11:23:51.797|Info|IndexingService.IndexTracksAsync|290|Tracks removed: 0. Time required: 2 ms +++
2020-03-11 11:23:51.805|Info|IndexingService.IndexTracksAsync|300|Tracks updated: 0. Time required: 2 ms +++
2020-03-11 11:23:52.939|Info|IndexingService.IndexTracksAsync|307|Tracks added: 3126. Time required: 1134 ms +++
2020-03-11 11:23:52.939|Info|IndexingService.IndexTracksAsync|314|+++ FINISHED INDEXING COLLECTION: Tracks removed: 0. Tracks updated: 0. Tracks added: 3126. Time required: 1144 ms +++
2020-03-11 11:23:52.939|Info|IndexingService.CleanupArtworkAsync|651|+++ STARTED CLEANING UP ARTWORK +++
2020-03-11 11:23:52.941|Info|IndexingService.CleanupArtworkAsync|672|+++ FINISHED CLEANING UP ARTWORK: Covers deleted from database: 0. Covers deleted from disk: 0. Time required:  ms +++
2020-03-11 11:23:52.941|Info|IndexingService.IndexCollectionAsync|227|Sending event to refresh the lists because: isTracksChanged = True, isArtworkCleanedUp = False
2020-03-11 11:23:52.941|Info|IndexingService.AddArtworkInBackgroundAsync|707|+++ STARTED ADDING ARTWORK IN THE BACKGROUND +++
2020-03-11 11:23:57.368|Error|IndexingService.AddArtworkInBackgroundAsync|815|+++ FINISHED ADDING ARTWORK IN THE BACKGROUND. Time required: 4427 ms +++
2020-03-11 11:23:57.368|Info|IndexingService.AddArtworkInBackgroundAsync|707|+++ STARTED ADDING ARTWORK IN THE BACKGROUND +++
2020-03-11 11:24:01.936|Error|IndexingService.AddArtworkInBackgroundAsync|815|+++ FINISHED ADDING ARTWORK IN THE BACKGROUND. Time required: 4568 ms +++
2020-03-11 11:24:04.222|Error|App.xaml.ExecuteEmergencyStop|541|Unhandled Exception. Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrumShapes()
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrum()
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Stack trace:
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrumShapes()
   at Dopamine.Controls.SpectrumAnalyzer.UpdateSpectrum()
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2020-03-11 11:24:04.222|Info|App.xaml.ExecuteEmergencyStop|544|### FORCED STOP of Dopamine, version 2.0.1.4000 ###
2020-03-11 11:24:04.388|Info|Shell.xaml.Window_Closing|123|### STOPPING Dopamine, version 2.0.1.4000 ###
2020-03-11 11:24:04.391|Info|LifetimeService.PerformClosingTasksAsync|25|Performing closing tasks
2020-03-11 11:24:04.392|Info|LifetimeService.PerformClosingTasksAsync|30|Write settings. Time required: 1 ms
2020-03-11 11:24:04.408|Info|Shell.xaml.Window_Closed|353|### STOPPED Dopamine, version 2.0.1.4000 ###
