### ISSUE TITLE
Unable to play songs if album folder renamed

### ISSUE THREAD

**Issue by o7burmajones** [digimezzo/dopamine-windows#1311]
## I'm submitting a...

<pre><code>
[x] Regression 
[ ] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 10, 21H1
* Dopamine version: 2.0.8

## Reproduction steps

* Step 1 - From desktop, extract compressed folder
* Step 2 - Rename folder
* Step 3 - Move folder from desktop into music directory
* Step 4 - Attempt playing any song from newly added folder

## Observed behavior

It doesn't respond at all. No error pop-up, no playback, etc. I've never encountered this before. Looking at the log file, it's like it's trying to find the file as if the folder wasn't renamed. 

If I open up dopamine, and try to play any of the songs from the artist, genre, album or songs tab, it won't work, but if I play from the folder tab, it will work.
## Desired behavior

It should play the song/album.
## Log file

2021-05-21 20:26:50.367|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\Nile\Nile 2019 - Vile Nilotic Rites\01 - Long Shadows Of Dread.mp3. EventMode=False, ExclusiveMode=False, LoopMode=All, Shuffle=False. Exception: File 'D:\Music\Nile\Nile 2019 - Vile Nilotic Rites\01 - Long Shadows Of Dread.mp3' was not found. StackTrace:    at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-21 20:26:51.957|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\Nile\Nile 2019 - Vile Nilotic Rites\01 - Long Shadows Of Dread.mp3. EventMode=False, ExclusiveMode=False, LoopMode=All, Shuffle=False. Exception: File 'D:\Music\Nile\Nile 2019 - Vile Nilotic Rites\01 - Long Shadows Of Dread.mp3' was not found. StackTrace:    at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-21 20:26:56.983|Info|PlaybackService.SaveQueuedTracksAsync|503|Saved 11 queued tracks

**Comment by o7burmajones** [comment]
If I go to manage collections and refresh now, it will work again.
