### ISSUE TITLE
Dopamine will not play any audio file

### ISSUE THREAD

**Issue by jed-development** [digimezzo/dopamine-windows#1312]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: 21H1 (Build 19043.985)
* Dopamine version: 2.0.8

## Reproduction steps

* Step 1 - Open an audio file, or open Dopamine and attempt to play a file from within Dopamine

## Observed behavior

The micro player will display blank, only showing the UI buttons, no song playing or song name visible. (Blank UI Screenshot: https://i.imgur.com/JrIMl86.png) In the main view, it shows a song but will not play it (Main View Screenshot: https://i.imgur.com/qTrwr7n.png), and in the showcase it shows a completely different song to the main view, which will also not play (Showcase Screenshot: https://i.imgur.com/LeJbUc1.png). No matter what file is attempted to be played whether launched from file explorer or from inside the player, it will not play. This only started yesterday, 22/05/2021, I have also attempted to reinstall Dopamine and remove/re-add my collection, did not help.

## Desired behavior

It should play the audio files.
## Log file

I have included several examples from the log file:

2021-05-23 16:15:53.342|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\01 Pa' La Cultura.mp3. EventMode=False, ExclusiveMode=False, LoopMode=One, Shuffle=True. Exception: IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".. StackTrace:    at CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, AudioDevice audioDevice)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-23 16:15:54.825|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\Y-Z\Yazoo\2008 - In Your Room\1.Upstairs At Eric's (Remaster)\02 Too Pieces.mp3. EventMode=False, ExclusiveMode=False, LoopMode=One, Shuffle=True. Exception: IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".. StackTrace:    at CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, AudioDevice audioDevice)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-23 16:15:58.146|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\Y-Z\Yazoo\1993 - The Classic Techno Mixes\02- Don't Go (Class X Remix).mp3. EventMode=False, ExclusiveMode=False, LoopMode=One, Shuffle=True. Exception: IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".. StackTrace:    at CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, AudioDevice audioDevice)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-23 16:15:59.472|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\Y-Z\Yazoo\1993 - The Classic Techno Mixes\02- Don't Go (Class X Remix).mp3. EventMode=False, ExclusiveMode=False, LoopMode=One, Shuffle=True. Exception: IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".. StackTrace:    at CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, AudioDevice audioDevice)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-23 16:15:59.870|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\Y-Z\Yazoo\1993 - The Classic Techno Mixes\02- Don't Go (Class X Remix).mp3. EventMode=False, ExclusiveMode=False, LoopMode=One, Shuffle=True. Exception: IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".. StackTrace:    at CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, AudioDevice audioDevice)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-23 16:16:00.037|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\Y-Z\Yazoo\1993 - The Classic Techno Mixes\02- Don't Go (Class X Remix).mp3. EventMode=False, ExclusiveMode=False, LoopMode=One, Shuffle=True. Exception: IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".. StackTrace:    at CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, AudioDevice audioDevice)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()
2021-05-23 16:16:05.118|Info|PlaybackService.SaveQueuedTracksAsync|503|Saved 10425 queued tracks
2021-05-23 16:16:07.256|Error|CacheService.CacheArtworkAsync|95|Could not cache byte[] artwork. Exception: Parameter is not valid.
2021-05-23 16:16:21.157|Error|CacheService.CacheArtworkAsync|95|Could not cache byte[] artwork. Exception: Parameter is not valid.
2021-05-23 16:16:24.823|Error|CacheService.CacheArtworkAsync|95|Could not cache byte[] artwork. Exception: Parameter is not valid.
2021-05-23 16:16:24.846|Error|CacheService.CacheArtworkAsync|95|Could not cache byte[] artwork. Exception: Parameter is not valid.
2021-05-23 16:16:30.694|Error|IndexingService.AddArtworkInBackgroundAsync|815|+++ FINISHED ADDING ARTWORK IN THE BACKGROUND. Time required: 43050 ms +++
2021-05-23 16:16:30.695|Info|IndexingService.AddArtworkInBackgroundAsync|707|+++ STARTED ADDING ARTWORK IN THE BACKGROUND +++
2021-05-23 16:22:17.075|Error|IndexingService.AddArtworkInBackgroundAsync|815|+++ FINISHED ADDING ARTWORK IN THE BACKGROUND. Time required: 346381 ms +++

2021-05-23 16:24:13.956|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\A-B\Alexander Rybak\Alexander Rybak - Fairytale.mp3. EventMode=False, ExclusiveMode=False, LoopMode=One, Shuffle=True. Exception: IMMDevice::Activate caused an error: 0x88890004, "Unknown HRESULT".. StackTrace:    at CSCore.CoreAudioAPI.AudioClient.FromMMDevice(MMDevice device)
   at CSCore.SoundOut.WasapiOut.InitializeInternal()
   at CSCore.SoundOut.WasapiOut.Initialize(IWaveSource source)
   at Dopamine.Core.Audio.CSCorePlayer.InitializeSoundOut(IWaveSource soundSource)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename, AudioDevice audioDevice)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__183.MoveNext()

**Comment by jed-development** [comment]
I finally got it working again, after uninstalling Dopamine, doing an in-place Windows upgrade (instead of a clean install), using the Media Creation Tool, did a file search to remove all files relating to Dopamine, manually deleting any registry keys relating to Dopamine and resetting app defaults to Microsoft recommended. Not sure what fixed it, but at least it's working again. If I don't experience this issue again in the next few days I'll close this issue.
