### ISSUE TITLE
How should we handle corrupt tracks?

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#238]
Currently, the indexer ignores corrupt tracks. They are never added to the collection.
Corrupt tracks which are double clicked in explorer are not ignored. Dopamine tries to play them, but it can cause a crash. How should be handle corrupt tracks?

**Comment by motir** [comment]
IMHO Dopamine should never crash. If playing a corrupt track means you can crash - you should display a msg saying track is corrupt and skip it.

**Comment by digimezzo** [comment]
How to simulate a crash (extreme situation):

- Create a text file, rename it to test.mp3
- Double click in explorer => Dopamine tries to read it and crashes.

The crash is caused in cscore.dll.

TODO: investigate if we can catch such corrupt file before sending it to CSCore. If not, CSCore will need patching to catch such crash.

**Comment by Riajyuu** [comment]
I agree what @motir suggests.

**Comment by Riajyuu** [comment]
@digimezzo Hey. I have a solution here:
According to [sampling theory](https://en.wikipedia.org/wiki/Sampling_(signal_processing)#Theory), here is how to judge if a file is corrupt:

- If sample rate is zero, it must be corrupt;
- If bit rate is higher than half of sample rate, it should be also corrput as there is insufficient record position
- If it is equal or lower than half of sample rate, it should be just fine.

Note: I'm not sure if this suit all cases but very most cases should be included.

**Comment by filoe** [comment]
Where does CSCore crash?

**Comment by digimezzo** [comment]
@filoe I currently don't have an audio file which causes a crash. But I have had users with "crazy" files report crashes identical to the one below:

> 2017-05-07 09:08:42.860|Error|<TryPlayAsync>d__179.MoveNext|Could not play the file C:\Users\rapha\Desktop\test.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True. Exception: Interops::MFCreateSourceReaderFromURL caused an error: 0xc00d36c4, "The byte stream type of the given URL is unsupported.".. StackTrace:    at CSCore.MediaFoundation.MediaFoundationCore.CreateSourceReaderFromUrlNative(String url)
>    at CSCore.MediaFoundation.MediaFoundationDecoder..ctor(String url)
>    at Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
>    at Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
>    at Dopamine.Common.Audio.CSCorePlayer.Play(String filename, MMDevice outputDevice)
>    at Dopamine.Common.Services.Playback.PlaybackService.<>c__DisplayClass178_0.<StartPlaybackAsync>b__0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__178.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__179.MoveNext()
> 2017-05-07 09:08:43.054|Error|App.ExecuteEmergencyStop|Unhandled Exception. Exception:
> System.ArgumentNullException: Value cannot be null.
>    at System.Threading.Monitor.Enter(Object obj)
>    at CSCore.Win32.ComObject.Finalize()

That exception occurs when trying to play a TXT file which was renamed to MP3. It is an extreme case of course, and is not supposed to work. However, real audio files (which are corrupt) can also cause this exception. So I wonder if it is possible to catch the error gracefully and avoid a crash of applications which use CSCore. I admit I haven't looked into the CSCore code myself yet, that is why this issue is still open.

**Comment by filoe** [comment]
Well, you still can catch the exception. Or am I wrong?

**Comment by digimezzo** [comment]
I'm not sure yet. I thought the whole SoundOut initialization is in a try catch in Dopamine, but apparently it crashes anyway. I'll have a more detailed look soon.
