### ISSUE TITLE
In still unknown cases, playback of the curent track is stopped mid-track and the next track starts playing

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#348]
One user has reported this issue. It is yet unclear what can cause this issue. The logs don't tell us anything useful. Extra logging was added, so that future builds will tell us if playback of the next or previous track was requested by the user itself. This is the report from the user:

> I hav already hinted u abt this bug but this time it has increased its frequency n is creating mess over here! 
> I did select a track(1) to b played bt suddenly it did jump to a file(2) from a different album n did pause all its playback n remained idle! Pls do take this issue with at most attention as this is a very much annoying bug!

More info from the user:

> I mean the tracks getting skipped off n dopamine remains idle!!!

![untitledaaaa](https://cloud.githubusercontent.com/assets/11945339/23857625/30952c9c-07fe-11e7-86f7-36f278d22c56.png)

This is all that is logged:

> 2017-03-12 22:01:28.128|Info|App.ExecuteStartup|### STARTING Dopamine, version 1.3.0.901, IsPortable = False, Windows version = Microsoft Windows 10 Pro (Microsoft Windows NT 10.0.14393.0) ###
> 2017-03-12 22:01:51.558|Info|Bootstrapper.InitializeWCFServices|CommandService was started successfully
> 2017-03-12 22:01:51.605|Info|Bootstrapper.InitializeWCFServices|FileService was started successfully
> 2017-03-12 22:01:51.667|Info|Bootstrapper.InitializeShell|Showing Main screen
> 2017-03-12 22:02:08.196|Info|<SaveQueuedTracksAsync>d__137.MoveNext|Saved 5 queued tracks
> 2017-03-12 22:02:09.039|Info|<TryPlayAsync>d__171.MoveNext|Playing the file F:\Audio\Tamil\Bairavaa\Varlaam_Varlaam_Vaa-StarMusiQ.Com.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True
> 2017-03-12 22:03:08.183|Info|<TryPlayAsync>d__171.MoveNext|Playing the file F:\Audio\Tamil\Bairavaa\Azhagiya_Soodana_Poovey-StarMusiQ.Com.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True
> 2017-03-12 22:03:18.386|Info|<TryPlayAsync>d__171.MoveNext|Playing the file F:\Audio\Malayalam\Makante Achan\02_ee_vennilavinte.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True

The audio file which caused this issue was verified, and plays fine on my computer (it doesn't stop mid-track). Also, this issue occurs with other files. So it doesn't seem file related.

**Comment by digimezzo** [comment]
I'm starting to suspect this is caused by audio driver issues. This user is having other issues: sometims, some files fail to play and just cause cscore to throw an exception:

>2017-03-18 14:10:41.479|Error|<TryPlayAsync>d__171.MoveNext|Could not play the file F:\Audio\Hindi\Chennai-Express-2013-320Kbps(Songs.PK)\Vishnu and CHENNAI EXPRESS lung dance.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=True. Exception: Object reference not set to an instance of an object.. StackTrace:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at CSCore.TimeConverterFactory.GetTimeConverterForSourceType(Type sourceType)
   at CSCore.Extensions.GetTime(IAudioSource source, Int64 elementCount)
   at Dopamine.Common.Audio.CSCorePlayer.GetCurrentTime()
   at Dopamine.Common.Services.Playback.PlaybackService.get_GetCurrentTime()
   at Dopamine.Common.Presentation.ViewModels.ProgressControlsWithTimeViewModel.GetPlayBackServiceProgress()
   at Dopamine.Common.Presentation.ViewModels.ProgressControlsViewModel.<.ctor>b__9_3(Boolean _)
   at System.Action`1.Invoke(T obj)
   at Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__171.MoveNext()

The file from the log above, doesn't cause this exception on my computer, using the same version of Dopamine.
