### ISSUE TITLE
Can't play ALAC m4a files on Win7

### ISSUE THREAD

**Issue by Aemony** [digimezzo/dopamine-windows#417]
It seems that Dopamine is unable to play Apple Lossless encoded m4a files on Windows 7, probably because the OS itself doesn't support it. Dopamine will fail to play the tracks even if a user have installed a third-party codec which makes even WMP play the files correctly.

Is there a way to solve this?

v1.3 build 918

```
2017-05-19 16:38:29.658|Error|<TryPlayAsync>d__179.MoveNext|Could not play the file E:\Cloud Storage\OneDrive\Music\Woodkid; Iron EP\Iron EP - 01 - Woodkid - Iron.m4a. EventMode=False, ExclusiveMode=False, LoopMode=All, Shuffle=False. Exception: IMFSourceReader::SetCurrentMediaType caused an error: 0xc00d5212, "Unknown HRESULT".. StackTrace:    at CSCore.MediaFoundation.MFSourceReader.SetCurrentMediaType(Int32 streamIndex, MFMediaType mediaType)
   at CSCore.MediaFoundation.MediaFoundationDecoder.Initialize(MFSourceReader reader)
   at CSCore.MediaFoundation.MediaFoundationDecoder..ctor(String url)
   at CSCore.Codecs.CodecFactory.GetCodec(String filename)
   at Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
   at Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
   at Dopamine.Common.Audio.CSCorePlayer.Play(String filename, MMDevice outputDevice)
   at Dopamine.Common.Services.Playback.PlaybackService.<>c__DisplayClass178_0.<StartPlaybackAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__178.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__179.MoveNext()
```

**Comment by digimezzo** [comment]
ALAC files are not supported by Windows Media Foundation (which is used to play audio in Dopamine).
In a next version, which should use ffmpeg to play audio, this file format should be supported.
Ffmpeg integration is currently planned for Dopamine 1.4.

**Comment by digimezzo** [comment]
Dopamine 1.5 will be released in a few days. Could you test these m4a files with that version and report back here? Thanks.

**Comment by Aemony** [comment]
Will do!

**Comment by Aemony** [comment]
Oh my god, now I feel utterly stupid. I expected my Dopamine v1.4 Preview build 958 to automatically update further to v1.5 but it didn't do that at all on any of my clients, so I thought that you had just delayed v1.5 until later. Seems the update check doesn't work in that version any longer.

> 2017-12-20 16:12:00.475|Info|UpdateService.EnableUpdateCheck|458|Update check: checking for updates. AlsoCheckForPreReleases = True
2017-12-20 16:12:00.475|Info|UpdateService.CheckForUpdatesAsync|350|Update check: current version = 1.4.0.958
2017-12-20 16:12:00.476|Info|UpdateService.EnableUpdateCheck|458|Update check: checking for updates. AlsoCheckForPreReleases = True
2017-12-20 16:12:00.837|Error|UpdateService.GetLatestOnlineVersionAsync|177|Update check: could not retrieve online version information. Exception: The remote server returned an error: (404) Not Found.
2017-12-20 16:12:00.837|Info|UpdateService.CheckForUpdatesAsync|356|Update check: latest online version = 0.0.0.0
2017-12-20 16:12:00.837|Info|UpdateService.CheckForUpdatesAsync|441|Update check: no newer version was found.

I'll be updating manually and test the feature out on my Windows 7 in a short while.

**Comment by digimezzo** [comment]
The update API was changed on the server with the release of 1.5. So 1.3 and 1.4 don't notify of updates anymore. But starting from 1.5, you'll get update notifications again.

**Comment by Aemony** [comment]
Sorry for the delay, but I've finally been able to confirm that playing ALAC m4a files now work perfectly on Windows 7. 😀
