### ISSUE TITLE
Crash when accessing Settings > Startup

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#504]
A user reported this:

When I go to settings and then click on startup, Dopamine crashes, every time.
Crash log:

> 2017-09-29 09:46:08.852|Error|App.xaml.ExecuteEmergencyStop|213|Unhandled Exception. Exception:
> System.ObjectDisposedException: Cannot access a disposed object.
>    at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
>    at System.Timers.Timer.set_Interval(Double value)
>    at Dopamine.Common.Services.Update.UpdateService.EnableUpdateCheck()
>    at Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.set_CheckBoxCheckForUpdatesChecked(Boolean value)
>    at Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>b__26_0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> Stack trace:
>    at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
>    at System.Timers.Timer.set_Interval(Double value)
>    at Dopamine.Common.Services.Update.UpdateService.EnableUpdateCheck()
>    at Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.set_CheckBoxCheckForUpdatesChecked(Boolean value)
>    at Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>b__26_0()
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by digimezzo** [comment]
This bug cannot be reproduced. The user has been asked to provide more info.
Also, the piece of code where is occurs should not cause an ObjectDisposedException exception, unless .NET internally decides to dispose the timer for some reason.

**Comment by jls2933** [comment]
Same problem occured in my instance :

````
2017-11-14 11:42:23.910|Info|UpdateService.EnableUpdateCheck|458|Update check: checking for updates. AlsoCheckForPreReleases = True
2017-11-14 11:42:23.936|Error|App.xaml.ExecuteEmergencyStop|213|Unhandled Exception. Exception:
System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
   à System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   à System.Timers.Timer.set_Interval(Double value)
   à Dopamine.Common.Services.Update.UpdateService.EnableUpdateCheck()
   à Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.set_CheckBoxCheckForUpdatesChecked(Boolean value)
   à Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>b__26_0()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>d__26.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Stack trace:
   à System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   à System.Timers.Timer.set_Interval(Double value)
   à Dopamine.Common.Services.Update.UpdateService.EnableUpdateCheck()
   à Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.set_CheckBoxCheckForUpdatesChecked(Boolean value)
   à Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>b__26_0()
   à System.Threading.Tasks.Task.Execute()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   à Dopamine.SettingsModule.ViewModels.SettingsStartupViewModel.<GetCheckBoxesAsync>d__26.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2017-11-14 11:42:23.936|Info|App.xaml.ExecuteEmergencyStop|216|### FORCED STOP of Dopamine, version 1.4.0.958 ###
2017-11-14 11:42:24.069|Info|Shell.xaml.PerformClosingTasksAsync|710|Performing closing tasks
````
