### ISSUE TITLE
'Could not play the file' error in 1.5.1

### ISSUE THREAD

**Issue by Keith94** [digimezzo/dopamine-windows#563]
>2017-11-20 14:08:18.073|Info|App.xaml.ExecuteStartup|56|### STARTING Dopamine, version 1.5.1.0, IsPortable = True, Windows version = Microsoft Windows 10 Pro (Microsoft Windows NT 10.0.16299.0), IsWindows10 = True ###
2017-11-20 14:08:19.014|Info|Bootstrapper.InitializeWCFServices|245|CommandService was started successfully
2017-11-20 14:08:19.015|Info|Bootstrapper.InitializeWCFServices|260|FileService was started successfully
2017-11-20 14:08:19.015|Info|Bootstrapper.InitializeShell|227|Showing Main screen
2017-11-20 14:08:19.151|Info|IndexingService.CheckCollectionAsync|143|+++ STARTED CHECKING COLLECTION +++
2017-11-20 14:08:19.549|Info|UpdateService.Reset|420|Resetting update check
2017-11-20 14:08:19.549|Info|UpdateService.DisablePeriodicCheck|413|Disabling periodic update check
2017-11-20 14:08:19.560|Info|UpdateService.CheckNow|259|Checking for updates
2017-11-20 14:08:19.560|Info|UpdateService.CheckNow|264|Update check: current version = 1.5.1.0
2017-11-20 14:08:19.862|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\02 クラブナイトメア.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False. Exception: avformat_open_input returned 0xffffffea: Invalid argument. StackTrace:    at CSCore.Ffmpeg.FfmpegCalls.AvformatOpenInput(AVFormatContext** formatContext, String url)
   at CSCore.Ffmpeg.AvFormatContext..ctor(String url)
   at CSCore.Ffmpeg.FfmpegDecoder..ctor(String url)
   at Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
   at Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__185.MoveNext()
2017-11-20 14:08:20.286|Info|IndexingService.AddArtworkInBackgroundAsync|741|+++ STARTED ADDING ARTWORK IN THE BACKGROUND +++
2017-11-20 14:08:20.331|Error|IndexingService.AddArtworkInBackgroundAsync|837|+++ FINISHED ADDING ARTWORK IN THE BACKGROUND. Time required: 41 ms +++
2017-11-20 14:08:20.538|Info|UpdateService.CheckNow|273|Update check: new online version = 0.0.0.0...
2017-11-20 14:08:20.538|Info|UpdateService.CheckNow|394|No new version was found
2017-11-20 14:08:22.970|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\01 さくらさくら.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False. Exception: avformat_open_input returned 0xffffffea: Invalid argument. StackTrace:    at CSCore.Ffmpeg.FfmpegCalls.AvformatOpenInput(AVFormatContext** formatContext, String url)
   at CSCore.Ffmpeg.AvFormatContext..ctor(String url)
   at CSCore.Ffmpeg.FfmpegDecoder..ctor(String url)
   at Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
   at Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__185.MoveNext()
2017-11-20 14:08:26.543|Error|PlaybackService.TryPlayAsync|1157|Could not play the file D:\Music\01 さくらさくら.mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False. Exception: avformat_open_input returned 0xffffffea: Invalid argument. StackTrace:    at CSCore.Ffmpeg.FfmpegCalls.AvformatOpenInput(AVFormatContext** formatContext, String url)
   at CSCore.Ffmpeg.AvFormatContext..ctor(String url)
   at CSCore.Ffmpeg.FfmpegDecoder..ctor(String url)
   at Dopamine.Common.Audio.CSCorePlayer.GetCodec(String filename)
   at Dopamine.Common.Audio.CSCorePlayer.Play(String filename)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Common.Services.Playback.PlaybackService.<StartPlaybackAsync>d__184.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Common.Services.Playback.PlaybackService.<TryPlayAsync>d__185.MoveNext()

**Comment by digimezzo** [comment]
Fixed by 2ae8eda26b3c504bd0a576159bf3654a88209f70

**Comment by Keith94** [comment]
New build soon?

**Comment by digimezzo** [comment]
Yes. Tonight or tomorrow.
