### ISSUE TITLE
CTD while attempting to add .wpl playlist to collection

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/dopamine-windows#58]
Dopamine isn’t set up to handle .wpl playlists, but it seems the exception isn’t caught, and Dopamine just instantly crashes to desktop instead of throwing an error message or something. I’ve linked the stack trace below. It’s easy to repro: just make a .wpl, force the import dialog to show it, and then try to import it.

> 2016-07-15 19:06:01.2563|Error|Dopamine.Common.Services.Collection.CollectionService+VB$StateMachine_18_OpenPlaylistAsync.MoveNext|Error while decoding playlist file. Exception: 
> 2016-07-15 19:06:01.2563|Error|Dopamine.Application.ExecuteEmergencyStop|Unhandled Exception. Exception:
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Dopamine.Core.Utils.ResourceUtils.GetStringResource(String iResourceName)
>    at Dopamine.CollectionModule.ViewModels.CollectionPlaylistsViewModel.VB$StateMachine_57_OpenPlaylistAsync.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.CollectionModule.ViewModels.CollectionPlaylistsViewModel.VB$StateMachine___Lambda$__51-1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> Stack trace:
>    at Dopamine.Core.Utils.ResourceUtils.GetStringResource(String iResourceName)
>    at Dopamine.CollectionModule.ViewModels.CollectionPlaylistsViewModel.VB$StateMachine_57_OpenPlaylistAsync.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Dopamine.CollectionModule.ViewModels.CollectionPlaylistsViewModel.VB$StateMachine___Lambda$__51-1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> 
> 2016-07-15 19:06:01.2673|Info|Dopamine.Application.ExecuteEmergencyStop|### FORCED STOP of Dopamine, version 1.0.0 (Build 584) ###
> 2016-07-15 19:06:01.2673|Info|Dopamine.Views.Shell+VB$StateMachine_110_PerformClosingTasksAsync.MoveNext|Performing closing tasks
> 2016-07-15 19:06:02.8988|Error|Axon.Axon.LifeBeatTimer_Elapsed|There was no LifeBeat for more than 1 seconds. Stopping now.

**Comment by digimezzo** [comment]
This is an old version of Dopamine. In the latest release, this bug cannot be reproduced.
