### ISSUE TITLE
Next Track Playback Error on Last Song

### ISSUE THREAD

**Issue by Alexander12444** [digimezzo/dopamine-windows#661]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro 1709 Build 16299.214
* Dopamine version: 1.5.10

## Reproduction steps

- start playing second to last song in an album/playlist/queue
- use the next track media key to play the last song in a queue

## Observed behavior

- 1/10 times: playback works as intended (usually happens on the first attempt, and rarely after)
- 4/10 times: it goes to the song but does not play it; cannot interact or play it, and there is no time info
- 5/10 times: it goes to the song but does not play it; cannot interact or play it, and time is 0:00/0:00
- if you try to play the song, it will instead skip to the first song as if the song had already ended

## Desired behavior

The last song should play normally.

## Log file

2018-02-12 09:39:18.132|Error|PlaybackService.TryPlayAsync|1182|Could not play the file E:\Music\Unitone\Unitone — THE 2 STORIES [MP3-V1][M3-39]\1.08. Nago — Skyrelief (lawy Remix).mp3. EventMode=False, ExclusiveMode=False, LoopMode=None, Shuffle=False. Exception: Cannot access a closed file.. StackTrace:    at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at CSCore.Ffmpeg.FfmpegStream.ReadDataCallback(IntPtr opaque, IntPtr buffer, Int32 bufferSize)
   at CSCore.Ffmpeg.Interops.ffmpeg.avformat_find_stream_info(AVFormatContext* ic, AVDictionary** options)
   at CSCore.Ffmpeg.FfmpegCalls.AvFormatFindStreamInfo(AVFormatContext* formatContext)
   at CSCore.Ffmpeg.AvFormatContext.Initialize()
   at CSCore.Ffmpeg.AvFormatContext..ctor(FfmpegStream stream)
   at CSCore.Ffmpeg.FfmpegDecoder..ctor(Stream stream)
   at Dopamine.Core.Audio.CSCorePlayer.GetCodec(String filename)
   at Dopamine.Core.Audio.CSCorePlayer.Play(String filename)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<StartPlaybackAsync>d__190.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dopamine.Services.Playback.PlaybackService.<TryPlayAsync>d__191.MoveNext()

**Comment by Alexander12444** [comment]
I'd like to bump this issue, as its behavior has changed but it's still been in every version of Dopamine  since and it's the last bug that prevents Dopamine from being perfect in my eyes.

Same reproduction steps, but now it plays the last track 4/5 times but still has 0:00/0:00 as the time, and cannot be moved to a different point in the song (the playing bar does not show progress and cannot be moved)

There is no info in the log file.

**Comment by digimezzo** [comment]
@Alexander12444 I can't reproduce this bug here. It works perfectly every time. Is is still happening with 2.0 Preview 14? Or there any specific things you're doing which I might be missing?

**Comment by Alexander12444** [comment]
Yes, it still happens. The error happens when using the hardware next track key, "MediaTrackNext" such as the dedicated media keys on a keyboard, and only when moving to the last track.
