### ISSUE TITLE
Crash When Attempting to Play an Empty Album Artist

### ISSUE THREAD

**Issue by Alexander12444** [digimezzo/dopamine-windows#976]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report  
[ ] Feature request
</code></pre>

## I'm using these versions

* Windows version: Windows 10 Pro 1809 Build 17763.475
* Dopamine version: Version 2.0 (Preview 7)

## Reproduction steps

* Step 1 In the artists page, scroll down until you find an album artist, which wouldn't have any albums to view when you click on it
* Step 2 Double click on it to start playing, which empties the now playing queue. The currently playing song will be set to #:##/0:00 (eg 2:14/0:00) in the bottom right corner, and now playing will say "Nothing is playing"
* Step 3 At the end of the song, dopamine will crash.

## Observed behavior

Dopamine crashes when the song finishes playing.

## Desired behavior

Dopamine should not crash. Also, having the album artist sorting tab back would be nice.

## Log file

2019-05-13 18:33:09.866|Error|App.xaml.ExecuteEmergencyStop|539|Unhandled Exception. Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dopamine.Services.Playback.PlaybackService.<<PlaybackFinishedHandler>b__188_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Stack trace:
   at Dopamine.Services.Playback.PlaybackService.<<PlaybackFinishedHandler>b__188_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

2019-05-13 18:33:09.867|Info|App.xaml.ExecuteEmergencyStop|542|### FORCED STOP of Dopamine, version 2.0.0.1007 ###
2019-05-13 18:33:09.896|Info|Shell.xaml.Window_Closing|124|### STOPPING Dopamine, version 2.0.0.1007 ###
2019-05-13 18:33:09.899|Info|LifetimeService.PerformClosingTasksAsync|25|Performing closing tasks
2019-05-13 18:33:09.905|Info|LifetimeService.PerformClosingTasksAsync|30|Write settings. Time required: 6 ms
2019-05-13 18:33:09.922|Info|Shell.xaml.Window_Closed|326|### STOPPED Dopamine, version 2.0.0.1007 ###

**Comment by digimezzo** [comment]
Would you mind sharing your Dopamine.db file and giving me an example of a artist which causes this issue. I wasn't able to reproduce this issue here yet.

**Comment by Alexander12444** [comment]
[Dopamine.zip](https://github.com/digimezzo/Dopamine/files/3219912/Dopamine.zip)

I downgraded back to preview 6 just to get album artists back, but i downloaded preview 7 portable and added just one album to test it.

The name used in the album artist field must not be the same as any of the artists, otherwise it will play songs that have the same name in the artist and album artist field and no bug will occur.

In this example, all of the songs have different artists, however the album is under the label wavforme and as such they all have wavforme in the album artist field. If I click on any of the artists on the side, they will all show the song from that artist in the album; however, if I click on the album artist wavforme, it will show as empty, as wavforme is only in the album artist field and does not have any songs.

If I double click on "wavforme" in the left side artist bar to queue the playing of all songs (none) by that artist, two things may occur, depending on how my music is tagged.

1. If there were any songs that also had wavforme in the artist field, those would start playing next, and no bug would occur. 

2. Only if there are no songs that have both fields populated by the same name will it crash upon the end of the currently playing song, as there is nothing to play.

If you were to remove the album artist field from the artist tab so it wouldn't show at all, it wouldn't be a problem. Right now there is no convenient way to see albums from only one album artist. Adding an album artist tab on the top would bring back functionality while still being able to clear on what is shown.

**Comment by digimezzo** [comment]
This bug was fixed in 55e6d00d44b334a66f02405e1fde53365142449a
